### ISSUE TITLE
The "Gridsome Netlify CMS Guide" Are Wrong? (Y/N)

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [gridsome/gridsome.org#118]
I follow all the steps but when i going to 
``` http://localhost:8080/admin/ ```
I get empty `"404" page`

In the docs you wrote:
https://gridsome.org/docs/guide-netlify-cms/#4-netlify-cms-setup

> Create an `admin` directory inside the src

But Under Netlify CMS docs i find this ("static")
https://www.netlifycms.org/docs/add-to-your-site/

![image](https://user-images.githubusercontent.com/16711871/54965340-c9186600-4f78-11e9-8f83-378c157b1f57.png)

#### Also in this `youtube` tuturial also i find diff folder loaction/ files Structure :
https://www.youtube.com/watch?v=ryP1RMA7P9Y
![image](https://user-images.githubusercontent.com/16711871/54965433-2f9d8400-4f79-11e9-8127-de207757a04e.png)

Also here:
https://dev.to/mittalyashu/how-to-integrate-netlify-cms-with-gridsome-188a
https://github.com/mittalyashu/gridsome-starter-netlifycms/tree/master/static/admin

Related:
https://github.com/gridsome/gridsome/issues/273

Can you please take a look of this? Thanks

**Comment by Larsklopstra** [comment]
I'll look into it, could you share your `gridsome.config.js`?

**Comment by Larsklopstra** [comment]
I followed the instructions from the [Gridsome Netlify CMS plugin](https://gridsome.org/plugins/gridsome-plugin-netlify-cms) 🙄

**Comment by Ezra-Siton-UIX** [comment]
Now works better (maybe I forgot to commit the change).

Do I need to change these values? (Y/N)

https://github.com/Ezra-Siton-UIX/gridsome/blob/master/src/admin/config.yml

**Comment by Larsklopstra** [comment]
`name: Ezra-Siton-UIX` is incorrect, it has to be `github` in your case, the name points to your git provider.
