### ISSUE TITLE
Tailwind section docs needs update

### ISSUE THREAD

**Issue by dakshshah96** [gridsome/gridsome.org#137]
The [current version](https://gridsome.org/docs/assets-css#tailwind) of the Tailwind section seems to be outdated.

The author of the [gridsome-plugin-tailwindcss](https://github.com/brandonpittman/gridsome-plugin-tailwindcss) recommends not using the plugin anymore and instead using the method mentioned in their [blog post](https://www.brandonpittman.net/tailwind-purge-config) instead.

**Comment by robaxelsen** [comment]
@dakshshah96 thanks for pointing this out :+1: :smile: 

As it sounds like have a good grasp on this, would you be interested in making a PR with updated docs?

**Comment by iAmBentley** [comment]
I created a PR, [223](https://github.com/gridsome/gridsome.org/pull/223), for this section. Prior to knowing this issue had been raised. The PR doesn't remove the plugin portion, but I did update it with more information and added a section on how to install it manually, without a plugin.
