### ISSUE TITLE
gridsome.org page consumes high CPU when the active tab in Safari under Mojave

### ISSUE THREAD

**Issue by ggerard** [gridsome/gridsome.org#150]
https://gridsome.org/

Couldn't figure out why my fan was crazy while I was just thinking and looking at terminal. The gruesome tab was the highest in Activity Monitor.

Tabbing to another tab caused an immediate reduction in load and the fan calmed down.

I don't know if this is also a bug in gridsome proper but 100% reproducible across reboots.

10.14.3

**Comment by hjvedvik** [comment]
It's caused by SVG animations. But we will change them to normal CSS animations in the new design.
