### ISSUE TITLE
Links change the route when you right-click on them

### ISSUE THREAD

**Issue by purdx** [gridsome/gridsome.org#155]
I have just started to explore this project and it seems really good, thank you for that.

When you right-click on links in docs it change the route and goes to that page.

Step to reproduce:
- Go to [how it works](https://gridsome.org/docs/how-it-works/)
- Right-click or Ctrl+click on `Source plugins` link

**Comment by robaxelsen** [comment]
@purdx thx for reporting this. I was able to reproduce with Ctrl+click, but not with Right-click.

**Comment by purdx** [comment]
The problem with Right-click happens in Firefox.

**Comment by 12vanblart** [comment]
I'm not able to reproduce this in Firefox (dev) or Chrome (stable) for Windows at this time.

Can someone confirm if this is still an issue?

**Comment by samuelhorn** [comment]
Works as expected in latest Chrome & Firefox on Mac OS Catalina. Can't reproduce.

**Comment by zacnomore** [comment]
Fixed! https://github.com/gridsome/gridsome/pull/236
