### ISSUE TITLE
Layout Problems in Plugins Gallery

### ISSUE THREAD

**Issue by zacnomore** [gridsome/gridsome.org#185]
![Screenshot from 2019-05-29 20-26-29](https://user-images.githubusercontent.com/5839548/58600034-c5db7800-8250-11e9-9523-8531f29b7588.png)

This occurs specially on this plugin: https://gridsome.org/plugins/gridsome-source-firestore
At the viewport sizes 1036-851px.

Both on Firefox:
"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"

And Chrome:
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"

I attempted to create a reduced test case but all I could determine was that the first two tables are causing the issue. Removing them from the DOM resolves the issue.

**Comment by Dana94** [comment]
I found that solely removing the text from this `<td></td>` fixes this layout problem.
It seems the code in that cell is not in `<code></code>` tags like the others are.
![image](https://user-images.githubusercontent.com/20132264/62169765-2ccfe880-b2f7-11e9-808d-d3a628538522.png)

**Comment by Dana94** [comment]
I made a PR to fix the markdown syntax in the plugin readme. This should fix the problem.
https://github.com/u12206050/gridsome-source-firestore/pull/1

**Comment by tomtev** [comment]
Thank you @Dana94 :)

**Comment by Dana94** [comment]
I'm actually not sure if this is fixed @tomtev , I cannot figure out which table is causing the layout issue. 😞
