### ISSUE TITLE
Blank page for gridsome-plugin-rss

### ISSUE THREAD

**Issue by cyrilf** [gridsome/gridsome.org#201]
On this plugin page [https://gridsome.org/plugins/gridsome-plugin-rss](https://gridsome.org/plugins/gridsome-plugin-rss) you can see that the content is empty.

This is due to the fact that Algolia return an empty `readme` key.

You can see it close to the bottom of this screenshot:
![Screenshot from 2019-06-10 20-51-02](https://user-images.githubusercontent.com/1302282/59190976-87837880-8bc1-11e9-9936-49834beefe10.png)

**Comment by robaxelsen** [comment]
@cyrilf thanks for reporting this issue. This is a community plugin, not maintained by the gridsome theme. Think I found the problem though, and submitted a PR to fix: https://github.com/darthmeme/gridsome-plugin-rss/pull/5

**Comment by zacnomore** [comment]
@robaxelsen I see you reopened this but it looks like this issue is resolved, [this page](https://gridsome.org/plugins/gridsome-plugin-rss) now shows correctly.
