### ISSUE TITLE
Add LICENSE.txt

### ISSUE THREAD

**Issue by likern** [gridsome/gridsome.org#216]
Hello! Thank you for such a great work on **GridSome**.
I've seen your https://gridsome.org site and it's so _beautiful_!
I would want to use it for my web site / landing page / documentation.

Could you please add **LICENSE** to your project?
Under want conditions can I use this site as template?
And is it possible to use for commercial (potentially :joy:) web site?

**Comment by rriemann** [comment]
I would like to explore if this technology could be of any use for public institutions websites and would like to use this as a starting point for a demo. So some free software or creative commons license would be really nice.

**Comment by mtlynch** [comment]
Fixed in #349
