### ISSUE TITLE
Update site github version to 0.6.6

### ISSUE THREAD

**Issue by ahtee** [gridsome/gridsome.org#220]

**Comment by 12vanblart** [comment]
@ahtee Would you be able to provide additional details on what this pertains to or what needs to be updated?

**Comment by Dana94** [comment]
@ahtee Is your request to update the version (currently  v0.6.8) to reflect the [change log's](https://github.com/gridsome/gridsome/blob/master/gridsome/CHANGELOG.md) latest version number (v0.6.9) ?

**Comment by ahtee** [comment]
@Dana94 yes :) at the point I opened the issue, the newest release was 0.6.6 but what i meant was just $latest
