### ISSUE TITLE
Twitter handles not displayed on contributor profiles

### ISSUE THREAD

**Issue by codybarr** [gridsome/gridsome.org#268]
I noticed that the `contributors.yaml` file has a field for twitter handles, but it doesn't look like they're being displayed on contributor profiles. 

![image](https://user-images.githubusercontent.com/4359586/66431852-d19f2e00-e9ea-11e9-8308-7788570c01f1.png)

Is this intentional? If not I'll submit a quick PR for this.

**Comment by tomtev** [comment]
Not implemented yet. Feel free to make a PR :)

**Comment by mtlynch** [comment]
Fixed in #269
