### ISSUE TITLE
[Bug] - Layout issues on WordPress starter theme

### ISSUE THREAD

**Issue by Charlesbjerg** [gridsome/gridsome.org#316]
Seem to be having quite major layout issues on [this page](https://gridsome.org/starters/gridsome-word-press-and-bootstrap-starter). Tested it on Chrome and Firefox on Windows with the same outcome. 

![image](https://user-images.githubusercontent.com/17528695/70080687-e66cfc00-15fe-11ea-94ef-4ff64cf9e627.png)

**Comment by mtlynch** [comment]
Fixed in #321
