### ISSUE TITLE
rendering issue on one starters page

### ISSUE THREAD

**Issue by rriemann** [gridsome/gridsome.org#325]
I discovered a rendering problem at this page:

https://gridsome.org/starters/gridsome-word-press-and-bootstrap-starter/

I use a very recent firefox with the usual ad block plugins.

![Screenshot_20191214_121525](https://user-images.githubusercontent.com/111932/70848015-ecb76f80-1e6b-11ea-8ad6-d6de42f3534f.png)

**Comment by Erbenos** [comment]
I already made a fix in #321

**Comment by mtlynch** [comment]
Fixed in #321
