### ISSUE TITLE
Configuring Favicon (icon) for multiple resolutions

### ISSUE THREAD

**Issue by tedyoung** [gridsome/gridsome.org#328]
I'm trying to figure out the docs for specifying the icon (favicon) where I have separate files for each individual resolution (icon-32.png, icon-96.png, etc.). The docs at https://gridsome.org/docs/config/#icon show a property "precomposed" which isn't defined anywhere.

How do I specify the individual files without Gridsome resizing my images? For example, I want to specify a file for size 16, a different file for size 32, etc., but the examples aren't enough to help me figure this out.

**Comment by 12vanblart** [comment]
Hi - based on this example from the page linked: 
```
module.exports = {
  icon: {
    favicon: {
      src: './src/my-favicon.png',
      sizes: [16, 32, 96]
    },
    touchicon: {
      src: './src/my-touchicon.png',
      sizes: [76, 152, 120, 167],
      precomposed: true
    }
  }
}
```

I believe you could do something like this to indicate the sizes:

```
module.exports = {
  icon: {
    favicon: {
      src: './src/my-favicon16.png',
      sizes: [16]
    },
    favicon: {
      src: './src/my-favicon32.png',
      sizes: [32]
    },
    favicon: {
      src: './src/my-favicon96.png',
      sizes: [96]
    },
    touchicon: {
      src: './src/my-touchicon.png',
      sizes: [76, 152, 120, 167],
      precomposed: true
    }
  }
}
```

For `touchicon` it seems that the `precomposed` keyword is [for older versions of iOS](https://mathiasbynens.be/notes/touch-icons)
