### ISSUE TITLE
"addMetadata" is undefined for store

### ISSUE THREAD

**Issue by tincho425** [gridsome/gridsome.org#329]
Function 'addMetadata' is undefined in 'store' variable.  Only functions defined for 'store' are 'createUniqueId' and 'createReference'. Discovered trying to set a global metadata property with the value of a page ID.

**Comment by 12vanblart** [comment]
Hi - I'm not sure exactly what the error you're encountering is or how to duplicate it. 

Could you link to a repo where you're having this issue? Or a block of code that causes the issue? 

Thanks 🙂
