### ISSUE TITLE
Using Background Images with GraphQL

### ISSUE THREAD

**Issue by SahilMaharaj** [gridsome/gridsome.org#330]
I'd like to know how to query images from my markdown files frontmatter using GraphQL but in the case when the image is being used as a background image not as "g-image". I'd like to have my markdown files (blog post) cover image to have the post title overlaid on the cover image so I need to use a background image.

Any insight would be appreciated

**Comment by noxify** [comment]
Wrong repository - Please use for this kind of questions: https://github.com/gridsome/gridsome

There are already some open issues/feature requests for this topic:

* https://github.com/gridsome/gridsome/issues/678
* https://github.com/gridsome/gridsome/issues/108
* https://github.com/gridsome/gridsome/issues/411
