### ISSUE TITLE
Broken Github link in Quick Start

### ISSUE THREAD

**Issue by nathakits** [gridsome/gridsome.org#35]
In the Quick Start of the doc, `Edit this page on Github` external link is broken. It takes you to a 404 page.

Wrong link - `https://github.com/gridsome/gridsome.org/tree/master/docs.md`
Correct link - `https://github.com/gridsome/gridsome.org/tree/master/docs/README.md`

**Comment by tomtev** [comment]
Thanks :) Will be fixed in #28
