### ISSUE TITLE
cover_image error in Post.vue and Index.vue

### ISSUE THREAD

**Issue by wristtattoo** [gridsome/gridsome.org#356]
I keep getting a cover_image error in my Post.vue and Index.vue. I'm running a default Netlify CMS template for Gridsome install. The only way i can get my site to publish is to remove `cover_image (width: 759, height: 380, blur: 10)` from the <page-query> from both Index.vue and Post.vue pages.

I'm running @gridsome/cli v0.3.1 and gridsome v0.7.12

```
Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Unknown argument "width" on field "cover_image" of type "Post".

GraphQL request:71:18
70 |     content
71 |     cover_image (width: 900, blur: 40)
   |                  ^
72 |   }
    at Object.module.exports (/Users/Ter/wristtattoo-github/netlifycms-gridsome/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js:29:23)
```

Possible solutions i found here also doesn't work!
[https://germano.dev/fix-netlify-cms-paths-on-gridsome/](https://germano.dev/fix-netlify-cms-paths-on-gridsome/)

**Comment by RehanSaeed** [comment]
Did you find a resolution? I raised https://github.com/gridsome/gridsome/issues/1031.

**Comment by wristtattoo** [comment]
> Did you find a resolution? I raised [gridsome/gridsome#1031](https://github.com/gridsome/gridsome/issues/1031).

I haven't yet no. Thank you for reading/replying!

**Comment by wristtattoo** [comment]
> Did you find a resolution? I raised [gridsome/gridsome#1031](https://github.com/gridsome/gridsome/issues/1031).

Spent a bit more time with my site [terrywells.co.uk](https://terrywells.co.uk) today and sadly couldn't find a solution. I ended up gluing an image to the index.vue above all posts with a text field relating to the current weekly issue which works well, but it's not perfect! Happy to share the code.

**Comment by mtlynch** [comment]
Thanks for filing this!

It looks like this is being tracked in https://github.com/gridsome/gridsome/issues/1031, so I'm going to close this issue, as this repo is for bugs in the gridsome.org documentation site.
