### ISSUE TITLE
How to deploy Gridsome project to AWS Amplify

### ISSUE THREAD

**Issue by paolotim** [gridsome/gridsome.org#376]
I just tried to deploy a Gridsome project on AWS Amplify but got a build error. Does anyone have an example of how to edit the Build Settings in Amplify to make it work? Thanks

**Comment by ghwalker** [comment]
You can do a manual deploy. I haven't figured out yet how to get Gridsome to build correctly.

**Comment by paolotim** [comment]
I have been able to do it! Here is the build setting .yml file:

preBuild:
 commands:
  - npm install --global @gridsome/cli
  - npm install
build
 commands:
  - Gridsome build
artifacts:
 BaseDirectory: dist
 files:
  - '**/*'

Best

**Comment by ghwalker** [comment]
Thanks for your help! I still can't get it to build. It gives me the following error: 

Error: 'darwin-x64' binaries cannot be used on the 'linux-x64' platform. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'. 

I assume I can enter some commands to remove? Something like: npm uninstall -g node_modules/sharp/vendor --save before build?

Is your local build on Mac, PC or Linux?

Thanks!

**Comment by paolotim** [comment]
My local is on Mac. I started from Gridsome Portfolio Starter that has all the dependences properly set and deploy well both on Netlify and AWS Amplify and modified that as needed. Best

**Comment by ghwalker** [comment]
Thanks.

It’s weird that it works fine on deploy to netlify but not Amplify. Still playing around with build script. Found this reference to my particular error:
https://sharp.pixelplumbing.com/install#aws-lambda

**Comment by ghwalker** [comment]
Wooohoooo! Got it to work!

Here’s my build script:

version: 0.1
frontend:
phases:
preBuild:
commands:
- rm -rf node_modules/sharp
- npm install --arch=x64 --platform=linux sharp
- npm install --global @gridsome/cli
- npm install build
build:
commands:
- gridsome build
artifacts:
# IMPORTANT - Please verify your build output directory
baseDirectory: dist
files:
- '**/*'
cache:
paths:
- node_modules/**/*

Best,
Glenn

**Comment by mtlynch** [comment]
@paolotim - Does @ghwalker's [comment](https://github.com/gridsome/gridsome.org/issues/376#issuecomment-603854982) answer your question or is this issue still open?
