### ISSUE TITLE
Site works fine on Netlify but NOT AWS

### ISSUE THREAD

**Issue by ghwalker** [gridsome/gridsome.org#391]
For the life of me I can't figure out why a site I deploy to Netlify works fine and when I deploy using either Amplify or Up + Cloudformation the site breaks. It appears to be some sort of pathing problem. Is there something I need to add to Gridsome.config.js to make this thing work?

**Comment by mtlynch** [comment]
Hi @ghwalker! Sorry for the delay. It's easier for us to help if you share a link to your repo.

I'm closing this as, this repo is for bugs on the website, but you can reach out to the support channels of the [Gridsome Discord](https://discord.gg/daeay6n) if this is still an open issue.
