### ISSUE TITLE
Search documentation

### ISSUE THREAD

**Issue by srchulo** [gridsome/gridsome.org#396]
I'd love to see an example on how to search in Gridsome:

https://gridsome.org/docs/guide-search/
https://github.com/gridsome/gridsome.org/blob/master/docs/guide-search.md

Specifically, would it be possible to have some kind of SSR? For SEO reasons, I'd really like the search results to be on the page when they are loaded. However, I want every other page on the site to be pre-rendered.

I really like Gridsome with link prefetching and the optimized images, but is something like SSR for searches make Nuxt a better fit?

**Comment by milos5593** [comment]
@srchulo you can look into [this plugin](https://gridsome.org/plugins/gridsome-plugin-flexsearch) for integrating search into your website or [this starter repo](https://github.com/mrcrmn/docc/blob/master/src/components/Search.vue) that has a search component based on fuse.js

Additionally, Gridsome uses SSR to generate static HTML files that are 100% SEO friendly.

**Comment by srchulo** [comment]
Thanks for the references! So it looks like it's not possible to have search results in the DOM on page load, but I guess that makes sense since Gridsome renders all of the HTML files ahead of time.

**Comment by mtlynch** [comment]
Closing this, as it looks like the question has been resolved, but @srchulo please reopen if I've misunderstood.
