### ISSUE TITLE
Adding canonicalLink to blog post does not seem to add a canonical link to the page.

### ISSUE THREAD

**Issue by rasulkireev** [gridsome/gridsome.org#440]
I just created a new blog post for gridsome.org. I wanted to specify the canonical link for my site. After adding canonicalLink tag to .md file, I could not locate the canonical link on the page.

[My PR](https://github.com/gridsome/gridsome.org/pull/439)

**Comment by mtlynch** [comment]
It looks like that's a feature that was intended but never implemented. There are no other references to `canonicalLink` in the gridsome.org or gridsome repos.

You can set it manually like this:

```javascript
 metaInfo() {
    return {
      link: [{ rel: "canonical", href: "http://yourcanonicalurl.com" }],
    };
  }
```

**Comment by rasulkireev** [comment]
@mtlynch Can I add that metaInfo function from within the .md file? Cause that is what I am adding to the repo.
