### ISSUE TITLE
Built-in auto docs localization

### ISSUE THREAD

**Issue by valaria247** [gridsome/gridsome.org#452]
I haven't seen any open source documentation has this feature built-in except people use translate extensions on browsers.  
(that's rare or annoying otherwise does not care to translate as long as able to understand the main idea of page)
Also quite difficult task for non-profit projects and startup owners to make available local versions for their sites and docs.

However this feature must retain static site deployment capability and configurable to exclude languages that already translated manually. There're various translate services offer free APIs and other facilities etc.

Automatically detect visitor IP or country using third party service and redirect to local version of site too great if possible to implement somehow.

I aware that is difficult task due static deployment also i have seen some developers succesful efforts to bring various things to static through many ways so if you guys invent something then it'll be great for everyone and others definitely get benefit from that.

**Comment by mtlynch** [comment]
Thanks for filing this issue, @valaria247!

This repo is for the documentation website. Feature requests for Gridsome go to:

https://github.com/gridsome/gridsome/issues

This is also a very largely-scoped feature request, which makes it unlikely to be implemented. Geolocating visitors by IP and then using public translation APIs to translate text to different languages is pretty outside of Gridsome's scope.

I'm not an official Gridsome representative, just giving my personal opinion. You're welcome to re-file this on the core Gridsome repo if you'd like.
