### ISSUE TITLE
The possibility of using source-graphql plugin for client-side data

### ISSUE THREAD

**Issue by syz51** [gridsome/gridsome.org#473]
Hey guys. Since there's already the source-graphql plugin which stitches the remote graphql schema with the site schema, would it be possible to fetch data from the stitched schema dynamically, on the client side?

The current feature that's missing that I can think of may be the ability to pass in header authentication dynamically on the client side.

Forgive me if there's already a better way to handle client-side graphql api usage

**Comment by thetre97** [comment]
@syz51 Bit late answering this, but:
This is not possible using the source-graphql plugin. However, it is possible using a different GraphQL client client-side - i.e. using Apollo/GraphQL Request.

**Comment by syz51** [comment]
Thanks. Will try this functionality with apollo client
