### ISSUE TITLE
[Question] How to configure modes order

### ISSUE THREAD

**Issue by R9980** [gridsome/gridsome.org#483]
Currently gridsome homepage loads dark mode by default and able to toggle sepia and white after that.
Then how to change that modes order eg, white, sepia, dark (white by default)

Can you show me related code lines that i need to update?

**Comment by 12vanblart** [comment]
[This is the theme toggle component](https://github.com/gridsome/gridsome.org/blob/master/src/components/ToggleTheme.vue)

It looks to me that lines 51 through 55 are setting the initial theme based on your browser theme preferences when the component mounts. 
```js
async mounted() {
  // set default
  if (typeof window.__theme !== 'undefined') this.theme = window.__theme
}
```

If the theme isn't set in the browser, it defaults to `light` on lines 31 through 34: 

```js
data() {
  return {
    theme: 'light',
  }
},
```

**Comment by mtlynch** [comment]
Thanks for answering @TerabyteTiger!

@R9980 - if this is not resolved, feel free to reopen.
