### ISSUE TITLE
Translating gridsome.org to portuguese

### ISSUE THREAD

**Issue by nazarepiedady** [gridsome/gridsome.org#506]
I'm **Nazaré**, I live in a portuguese country located in **Africa** called **Angola**
.
I'm interested in all technologies that help us our work with Vue.js,
because this reason I want translate the main gridsome tecnology content
to my first language, this way helping the people that talk portuguese like me
learn the tecnhology in a more confortable way.
.
Only difficult that's I'm just start my Vue.js studies this days and I need someone that implement
the change language funcionality for me.

**Comment by tomtev** [comment]
Hey @nazarepiedady . Thanks for showing interest :)
We want to wait for translations until 1.0 is ready.
The English documentation will change a bit before then.

**Comment by nazarepiedady** [comment]
In this case, I will wait for all main changes or for 1.0 version, and then I will fork the website and documentation repository and start the translations 😉😊.
