### ISSUE TITLE
Can we use dynamic metaInfo

### ISSUE THREAD

**Issue by yanuaraditia** [gridsome/gridsome.org#529]
I've creating file-based dynamic page
`users/[id].vue`

When access the route, I've added async axios method to get user info. How can I update the `metainfo` after axios is completed?

**Comment by thetre97** [comment]
Check out the docs for [Vue Meta](https://vue-meta.nuxtjs.org) - in short, yes. It can be a function, which will then make it reactive:
```js
export default {
	metaInfo () {
		if (this.loading) return { title: 'Loading...' }
		return { title: `Welcome ${this.user.name}` }
	}
}
```

**Comment by thetre97** [comment]
@yanuaraditia Does the above answer your question? If so, can this comment be closed?
