### ISSUE TITLE
Will Gridsome Opt-in to Hacktoberfest? 

### ISSUE THREAD

**Issue by TerabyteTiger** [gridsome/gridsome.org#535]
I know we've already received a couple spam PRs for Hacktoberfest and completely understand if we don't want to do this - but with the [newest update](https://hacktoberfest.digitalocean.com/hacktoberfest-update) users will only get credit if we opt this repository in. 

If we do opt in - do we have a set response we should issue to spam PRs?

**Comment by TerabyteTiger** [comment]
There has been yet another update on this - we can now add a label of `hacktoberfest-accepted` to individual PRs if we don't want to set the whole repository as `hacktoberfest`. 

So updating my question - do we want to use either of these methods?

**Comment by hjvedvik** [comment]
Sorry for not answering you sooner, @TerabyteTiger. This month went by way too fast. I've added the label, so feel free to add it to PR's if you want to. And I'll give you permissions to approve or merge them :)

**Comment by TerabyteTiger** [comment]
It really did go too fast 😅 

I was away from when you posted this until now - but thanks!
