### ISSUE TITLE
Question regarding overriding App.vue 

### ISSUE THREAD

**Issue by wallythewebdev** [gridsome/gridsome.org#540]
Hi there - 

I have been following your DOCs found here: 
https://gridsome.org/docs/overriding-app/

With regards to creating a custom app.vue - 
the reason for wanting this is so I can control the router transition, however, it is useful to be able to control layouts for different pages in gridsome. 

I didn't get a clear sense if it was possible to create a custom App.vue, which is only intended to be used for router transitions but also be able to still have layouts on different pages? 

any input here would be great && is router transitions something that is going to be added to gridsome in future?

thanks in advance - 
W

**Comment by TerabyteTiger** [comment]
If I'm understanding correctly, I believe that if you use the last code block [here](https://gridsome.org/docs/overriding-app/#page-transitions) will add transitions, but still allow you to handle the Layout piece within the pages themselves.

**Comment by wallythewebdev** [comment]
I think that seems to have worked :) thanks
