### ISSUE TITLE
Request for contributing invitation.

### ISSUE THREAD

**Issue by duckstroms** [gridsome/gridsome.org#590]
Hey, Myself Andri Wahyudi (1st Hackerone Inc Leaderboard)

- [ ]  Python Programming Enthusiast
- [ ]  Penentration Testing / Vulnerability Analysis
- [ ]  Focus on Contributing more throughout the year

**Comment by thetre97** [comment]
Hey @duckstroms,

You are most welcome to contribute to this repository - anyone can create a PR, so feel free to do that and a maintainer can merge it in if appropriate.
